### ISSUE TITLE
Labels should alway be lowercase

### ISSUE THREAD

**Issue by JDA88** [opsdis/aci-exporter#26]
**Describe the bug**
The labels set by he user in the yaml fils can contain upercase

**Expected behavior**
As a best practice labels should always be lowercase

You can find regex to validates labels names and metric names in this issue for example: https://github.com/prometheus/client_java/issues/28

For label names maybe a `.ToLower()` could be an option and would minimise rework for existing files.
... But it might break existing queries

**Comment by thenodon** [comment]
@JDA88 thanks for reporting this. I agree with you that lower case is best practices, but I do not want to force that. A simple option is in the configuration add a variable, e.g. all_labels_to_lower, that is default false for backwards compatibility. If true it will make all labels lowercase. With this solution user can chose to go Prometheus best practices or keep label keys "compatible" how they are named in ACI.

**Comment by JDA88** [comment]
I agree forcing by defaut is probably a bad idea.
We faced the issue and we are correcting it at the prometheus relabeling level, but I just wanted to point it out.

**Comment by thenodon** [comment]
Fix in #31
