### ISSUE TITLE
Direct Switch Queries

### ISSUE THREAD

**Issue by camrossi** [opsdis/aci-exporter#58]
Currently all the data collected by aci-exporter comes from the APICs. 
This works great for small fabrics but at scale generates a lot of extra load on the APICs. 

A good example is interface statistics: aci-exporter collecting them for all the interfaces of all the switches and APIC becomes the bottle neck. 
A better approach would be to gather this data directly from the switches.

In order to do so we need to:

- Discover the switches (add/remove) 
- Add a new scrape target for every switch
- Allow the user to select oob or inband 
- Add a new query flag to select if the query should be directed to the APICs or to the switches 
- Enrich the data collected directly from the switches with the pod and switch ID as the dn returned by the switch directly dosen't contains that anymore.

**Comment by thenodon** [comment]
For anyone interested in the progress of this feature request checkout branch https://github.com/opsdis/aci-exporter/tree/issue_58_discovery. 
Please read the README.md, section "# Use aci-exporter in large fabric setups" and the `prometheus_nodes.yml` in the folder `prometheus`

**Comment by camrossi** [comment]
Hi @MilesTails,

There was a bug where connection re-use was not working correctly and was mixing up the connection resulting in metric from different switches to be mixed up. I wonder if that was what you where seeing as it did seems as metric labeling wasn't working correctly. It was only happening at scale as well and I saw it when testing on a 500 switch fabric. 

This is the commit: https://github.com/opsdis/aci-exporter/commit/0e3f000caae2d9c7f733bbb50513cbaf7fc33166

On a side note I am about to release in OpenSource a full monitoring stack for ACI based of aci-exporter and Prometheus, Loki, Grafana where I have already build a few dashboards, alerts and is all deployed with Helm. 
The idea is making it a community effort to try to build something "cool".
Once I do would you like me to let you know?

**Comment by MilesTails** [comment]
Hey @camrossi, ah that is probably it! I was seeing it in a sub-set of nodes in my biggest fabric ~250 nodes. Thank you so much for fixing :)

Regarding full stack deployment, we are already doing that internally, I've made a few dashboards and added/improved upon some of the quries/metrics and also building out alerting. I just need to get internal approval to submit my tiny modifications back. Not sure how much of that would be useful to you guys and what vision you have for breaking out like a "barebones" set of metrics and a more "enhanced" pack?

**Comment by thenodon** [comment]
Hi @MilesTails , great to here that you are testing the branch https://github.com/opsdis/aci-exporter/tree/issue_58_discovery, especially since you have a large fabric. If you have the time to test the branch against your fabric it would be great using the feature of direct spine/leaf metrics scraping.
I would also appreciate any feedback on the https://github.com/opsdis/aci-exporter/blob/issue_58_discovery/README.md when it comes to language and if its understandable :)
The goal is to try to release this new version in the end of the week, so any feedback our just "it works" is great.

**Comment by thenodon** [comment]
This issue is now implemented with the release of version 0.8.0, https://github.com/opsdis/aci-exporter/releases/tag/v0.8.0
