### ISSUE TITLE
up metrics continue 1 when aci node is unreachable.

### ISSUE THREAD

**Issue by minefuto** [opsdis/aci-exporter#72]
**Describe the bug**
`up` metrics continue 1 when aci node is unreachable(e.g. aci node down) using "node based queries".
I think if aci node is unreachable, `up` metrics shoud be goes to 0.

**To Reproduce**
1. Using node base queries.
2. Reboot one aci node.

**Additional context**
#70

**Comment by thenodon** [comment]
@minefuto I have made branch https://github.com/opsdis/aci-exporter/tree/issue_72 with what seems to work. I have tested but have not had the possibility to shutdown a node. Please give it a try.

**Comment by minefuto** [comment]
Thanks @thenodon 
I checked and it seems it is work normally.

**Comment by thenodon** [comment]
@minefuto this is now fixed in https://github.com/opsdis/aci-exporter/releases/tag/v0.8.1. Thanks for finding this issue.
